//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mcs.proto
namespace JodelNet.Verification.Proto
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"HeartbeatPing")]
    public partial class HeartbeatPing : global::ProtoBuf.IExtensible
    {
        public HeartbeatPing() { }

        private int _stream_id = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"stream_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int stream_id
        {
            get { return _stream_id; }
            set { _stream_id = value; }
        }
        private int _last_stream_id_received = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"last_stream_id_received", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int last_stream_id_received
        {
            get { return _last_stream_id_received; }
            set { _last_stream_id_received = value; }
        }
        private long _status = default(long);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long status
        {
            get { return _status; }
            set { _status = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"HeartbeatAck")]
    public partial class HeartbeatAck : global::ProtoBuf.IExtensible
    {
        public HeartbeatAck() { }

        private int _stream_id = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"stream_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int stream_id
        {
            get { return _stream_id; }
            set { _stream_id = value; }
        }
        private int _last_stream_id_received = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"last_stream_id_received", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int last_stream_id_received
        {
            get { return _last_stream_id_received; }
            set { _last_stream_id_received = value; }
        }
        private long _status = default(long);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long status
        {
            get { return _status; }
            set { _status = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ErrorInfo")]
    public partial class ErrorInfo : global::ProtoBuf.IExtensible
    {
        public ErrorInfo() { }

        private int _code;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int code
        {
            get { return _code; }
            set { _code = value; }
        }
        private string _message = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string message
        {
            get { return _message; }
            set { _message = value; }
        }
        private string _type = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string type
        {
            get { return _type; }
            set { _type = value; }
        }
        private Extension _extension = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Extension extension
        {
            get { return _extension; }
            set { _extension = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Setting")]
    public partial class Setting : global::ProtoBuf.IExtensible
    {
        public Setting() { }

        private string _name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        private string _value;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string value
        {
            get { return _value; }
            set { _value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"HeartbeatStat")]
    public partial class HeartbeatStat : global::ProtoBuf.IExtensible
    {
        public HeartbeatStat() { }

        private string _ip;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string ip
        {
            get { return _ip; }
            set { _ip = value; }
        }
        private bool _timeout;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"timeout", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool timeout
        {
            get { return _timeout; }
            set { _timeout = value; }
        }
        private int _interval_ms;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"interval_ms", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int interval_ms
        {
            get { return _interval_ms; }
            set { _interval_ms = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"HeartbeatConfig")]
    public partial class HeartbeatConfig : global::ProtoBuf.IExtensible
    {
        public HeartbeatConfig() { }

        private bool _upload_stat = default(bool);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"upload_stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool upload_stat
        {
            get { return _upload_stat; }
            set { _upload_stat = value; }
        }
        private string _ip = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ip
        {
            get { return _ip; }
            set { _ip = value; }
        }
        private int _interval_ms = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"interval_ms", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int interval_ms
        {
            get { return _interval_ms; }
            set { _interval_ms = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LoginRequest")]
    public partial class LoginRequest : global::ProtoBuf.IExtensible
    {
        public LoginRequest() { }

        private string _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private string _domain;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"domain", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string domain
        {
            get { return _domain; }
            set { _domain = value; }
        }
        private string _user;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string user
        {
            get { return _user; }
            set { _user = value; }
        }
        private string _resource;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string resource
        {
            get { return _resource; }
            set { _resource = value; }
        }
        private string _auth_token;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"auth_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string auth_token
        {
            get { return _auth_token; }
            set { _auth_token = value; }
        }
        private string _device_id = "";
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string device_id
        {
            get { return _device_id; }
            set { _device_id = value; }
        }
        private long _last_rmq_id = default(long);
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"last_rmq_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long last_rmq_id
        {
            get { return _last_rmq_id; }
            set { _last_rmq_id = value; }
        }
        private readonly global::System.Collections.Generic.List<Setting> _setting = new global::System.Collections.Generic.List<Setting>();
        [global::ProtoBuf.ProtoMember(8, Name = @"setting", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Setting> setting
        {
            get { return _setting; }
        }

        //private int _compress = default(int);
        //[global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"compress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        //[global::System.ComponentModel.DefaultValue(default(int))]
        //public int compress
        //{
        //    get { return _compress; }
        //    set { _compress = value; }
        //}
        private readonly global::System.Collections.Generic.List<string> _received_persistent_id = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(10, Name = @"received_persistent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> received_persistent_id
        {
            get { return _received_persistent_id; }
        }

        //private bool _include_stream_ids = default(bool);
        //[global::ProtoBuf.ProtoMember(11, IsRequired = false, Name = @"include_stream_ids", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(default(bool))]
        //public bool include_stream_ids
        //{
        //    get { return _include_stream_ids; }
        //    set { _include_stream_ids = value; }
        //}
        private bool _adaptive_heartbeat = default(bool);
        [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name = @"adaptive_heartbeat", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool adaptive_heartbeat
        {
            get { return _adaptive_heartbeat; }
            set { _adaptive_heartbeat = value; }
        }
        private HeartbeatStat _heartbeat_stat = null;
        [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name = @"heartbeat_stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public HeartbeatStat heartbeat_stat
        {
            get { return _heartbeat_stat; }
            set { _heartbeat_stat = value; }
        }
        private bool _use_rmq2 = default(bool);
        [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name = @"use_rmq2", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool use_rmq2
        {
            get { return _use_rmq2; }
            set { _use_rmq2 = value; }
        }
        private long _account_id = default(long);
        [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name = @"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long account_id
        {
            get { return _account_id; }
            set { _account_id = value; }
        }
        private int _auth_service = 2;
        [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name = @"auth_service", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int auth_service
        {
            get { return _auth_service; }
            set { _auth_service = value; }
        }
        private int _network_type = default(int);
        [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name = @"network_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int network_type
        {
            get { return _network_type; }
            set { _network_type = value; }
        }
        private long _status = default(long);
        [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name = @"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long status
        {
            get { return _status; }
            set { _status = value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LoginResponse")]
    public partial class LoginResponse : global::ProtoBuf.IExtensible
    {
        public LoginResponse() { }

        private string _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private string _jid = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"jid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string jid
        {
            get { return _jid; }
            set { _jid = value; }
        }
        private ErrorInfo _error = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ErrorInfo error
        {
            get { return _error; }
            set { _error = value; }
        }
        private readonly global::System.Collections.Generic.List<Setting> _setting = new global::System.Collections.Generic.List<Setting>();
        [global::ProtoBuf.ProtoMember(4, Name = @"setting", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Setting> setting
        {
            get { return _setting; }
        }

        private int _stream_id = default(int);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"stream_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int stream_id
        {
            get { return _stream_id; }
            set { _stream_id = value; }
        }
        private int _last_stream_id_received = default(int);
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"last_stream_id_received", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int last_stream_id_received
        {
            get { return _last_stream_id_received; }
            set { _last_stream_id_received = value; }
        }
        private HeartbeatConfig _heartbeat_config = null;
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"heartbeat_config", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public HeartbeatConfig heartbeat_config
        {
            get { return _heartbeat_config; }
            set { _heartbeat_config = value; }
        }
        private long _server_timestamp = default(long);
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"server_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long server_timestamp
        {
            get { return _server_timestamp; }
            set { _server_timestamp = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StreamErrorStanza")]
    public partial class StreamErrorStanza : global::ProtoBuf.IExtensible
    {
        public StreamErrorStanza() { }

        private string _type;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string type
        {
            get { return _type; }
            set { _type = value; }
        }
        private string _text = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string text
        {
            get { return _text; }
            set { _text = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Close")]
    public partial class Close : global::ProtoBuf.IExtensible
    {
        public Close() { }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Extension")]
    public partial class Extension : global::ProtoBuf.IExtensible
    {
        public Extension() { }

        private int _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int id
        {
            get { return _id; }
            set { _id = value; }
        }
        private byte[] _data;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] data
        {
            get { return _data; }
            set { _data = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"IqStanza")]
    public partial class IqStanza : global::ProtoBuf.IExtensible
    {
        public IqStanza() { }

        private long _rmq_id = default(long);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"rmq_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long rmq_id
        {
            get { return _rmq_id; }
            set { _rmq_id = value; }
        }
        private IqStanza.IqType _type;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public IqStanza.IqType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private string _id;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private string _from = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string from
        {
            get { return _from; }
            set { _from = value; }
        }
        private string _to = "";
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string to
        {
            get { return _to; }
            set { _to = value; }
        }
        private ErrorInfo _error = null;
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ErrorInfo error
        {
            get { return _error; }
            set { _error = value; }
        }
        private Extension _extension = null;
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"extension", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Extension extension
        {
            get { return _extension; }
            set { _extension = value; }
        }
        private string _persistent_id = "";
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"persistent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string persistent_id
        {
            get { return _persistent_id; }
            set { _persistent_id = value; }
        }
        private int _stream_id = default(int);
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"stream_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int stream_id
        {
            get { return _stream_id; }
            set { _stream_id = value; }
        }
        private int _last_stream_id_received = default(int);
        [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"last_stream_id_received", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int last_stream_id_received
        {
            get { return _last_stream_id_received; }
            set { _last_stream_id_received = value; }
        }
        private long _account_id = default(long);
        [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name = @"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long account_id
        {
            get { return _account_id; }
            set { _account_id = value; }
        }
        private long _status = default(long);
        [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name = @"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long status
        {
            get { return _status; }
            set { _status = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"IqType")]
        public enum IqType
        {

            [global::ProtoBuf.ProtoEnum(Name = @"GET", Value = 0)]
            GET = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"SET", Value = 1)]
            SET = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"RESULT", Value = 2)]
            RESULT = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"IQ_ERROR", Value = 3)]
            IQ_ERROR = 3
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"AppData")]
    public partial class AppData : global::ProtoBuf.IExtensible
    {
        public AppData() { }

        private string _key;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string key
        {
            get { return _key; }
            set { _key = value; }
        }
        private string _value;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string value
        {
            get { return _value; }
            set { _value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DataMessageStanza")]
    public partial class DataMessageStanza : global::ProtoBuf.IExtensible
    {
        public DataMessageStanza() { }

        private long _rmq_id = default(long);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"rmq_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long rmq_id
        {
            get { return _rmq_id; }
            set { _rmq_id = value; }
        }
        private string _id = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private string _from;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string from
        {
            get { return _from; }
            set { _from = value; }
        }
        private string _to = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string to
        {
            get { return _to; }
            set { _to = value; }
        }
        private string _category;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"category", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string category
        {
            get { return _category; }
            set { _category = value; }
        }
        private string _token = "";
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token
        {
            get { return _token; }
            set { _token = value; }
        }
        private readonly global::System.Collections.Generic.List<AppData> _app_data = new global::System.Collections.Generic.List<AppData>();
        [global::ProtoBuf.ProtoMember(7, Name = @"app_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<AppData> app_data
        {
            get { return _app_data; }
        }

        private bool _from_trusted_server = default(bool);
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"from_trusted_server", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(default(bool))]
        public bool from_trusted_server
        {
            get { return _from_trusted_server; }
            set { _from_trusted_server = value; }
        }
        private string _persistent_id = "";
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"persistent_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string persistent_id
        {
            get { return _persistent_id; }
            set { _persistent_id = value; }
        }
        private int _stream_id = default(int);
        [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"stream_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int stream_id
        {
            get { return _stream_id; }
            set { _stream_id = value; }
        }
        private int _last_stream_id_received = default(int);
        [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name = @"last_stream_id_received", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int last_stream_id_received
        {
            get { return _last_stream_id_received; }
            set { _last_stream_id_received = value; }
        }
        private string _permission = "";
        [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name = @"permission", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string permission
        {
            get { return _permission; }
            set { _permission = value; }
        }
        private string _reg_id = "";
        [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name = @"reg_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string reg_id
        {
            get { return _reg_id; }
            set { _reg_id = value; }
        }
        private string _pkg_signature = "";
        [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name = @"pkg_signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string pkg_signature
        {
            get { return _pkg_signature; }
            set { _pkg_signature = value; }
        }
        private string _client_id = "";
        [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name = @"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string client_id
        {
            get { return _client_id; }
            set { _client_id = value; }
        }
        private long _device_user_id = default(long);
        [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name = @"device_user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long device_user_id
        {
            get { return _device_user_id; }
            set { _device_user_id = value; }
        }
        private int _ttl = default(int);
        [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name = @"ttl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int ttl
        {
            get { return _ttl; }
            set { _ttl = value; }
        }
        private long _sent = default(long);
        [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name = @"sent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long sent
        {
            get { return _sent; }
            set { _sent = value; }
        }
        private int _queued = default(int);
        [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name = @"queued", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int queued
        {
            get { return _queued; }
            set { _queued = value; }
        }
        private long _status = default(long);
        [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name = @"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long status
        {
            get { return _status; }
            set { _status = value; }
        }
        private byte[] _raw_data = null;
        [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name = @"raw_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] raw_data
        {
            get { return _raw_data; }
            set { _raw_data = value; }
        }
        private int _delay = default(int);
        [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name = @"delay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int delay
        {
            get { return _delay; }
            set { _delay = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StreamAck")]
    public partial class StreamAck : global::ProtoBuf.IExtensible
    {
        public StreamAck() { }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SelectiveAck")]
    public partial class SelectiveAck : global::ProtoBuf.IExtensible
    {
        public SelectiveAck() { }

        private readonly global::System.Collections.Generic.List<string> _id = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> id
        {
            get { return _id; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"BindAccountRequest")]
    public partial class BindAccountRequest : global::ProtoBuf.IExtensible
    {
        public BindAccountRequest() { }

        private string _packetid = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"packetid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string packetid
        {
            get { return _packetid; }
            set { _packetid = value; }
        }
        private string _domain = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"domain", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string domain
        {
            get { return _domain; }
            set { _domain = value; }
        }
        private string _user = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string user
        {
            get { return _user; }
            set { _user = value; }
        }
        private string _resource = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string resource
        {
            get { return _resource; }
            set { _resource = value; }
        }
        private long _accountid = default(long);
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"accountid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long accountid
        {
            get { return _accountid; }
            set { _accountid = value; }
        }
        private string _token = "";
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token
        {
            get { return _token; }
            set { _token = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"BindAccountResponse")]
    public partial class BindAccountResponse : global::ProtoBuf.IExtensible
    {
        public BindAccountResponse() { }

        private string _packetid = "";
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"packetid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string packetid
        {
            get { return _packetid; }
            set { _packetid = value; }
        }
        private string _jid = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"jid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string jid
        {
            get { return _jid; }
            set { _jid = value; }
        }
        private int _laststreamid = default(int);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"laststreamid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int laststreamid
        {
            get { return _laststreamid; }
            set { _laststreamid = value; }
        }
        private int _streamid = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"streamid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int streamid
        {
            get { return _streamid; }
            set { _streamid = value; }
        }
        private ErrorInfo _error = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ErrorInfo error
        {
            get { return _error; }
            set { _error = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}